// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUtXWE4rhPFngnryZDrSBHI_vx7tLKJM',
    appId: '1:414915772944:web:bc7d21f04bbd61eb7ac095',
    messagingSenderId: '414915772944',
    projectId: 'servana-8a6f3',
    authDomain: 'servana-8a6f3.firebaseapp.com',
    storageBucket: 'servana-8a6f3.firebasestorage.app',
    measurementId: 'G-V2ZDXSCT7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhLOaIeQpZHb9feDRivwMz_hq3VvEmII',
    appId: '1:414915772944:android:75fa60509fdf77687ac095',
    messagingSenderId: '414915772944',
    projectId: 'servana-8a6f3',
    storageBucket: 'servana-8a6f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Z6d5hYzU3xhGqNSIYKf-Hg4c7N7l7yc',
    appId: '1:414915772944:ios:4cbbe3e1838e922e7ac095',
    messagingSenderId: '414915772944',
    projectId: 'servana-8a6f3',
    storageBucket: 'servana-8a6f3.firebasestorage.app',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Z6d5hYzU3xhGqNSIYKf-Hg4c7N7l7yc',
    appId: '1:414915772944:ios:4cbbe3e1838e922e7ac095',
    messagingSenderId: '414915772944',
    projectId: 'servana-8a6f3',
    storageBucket: 'servana-8a6f3.firebasestorage.app',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIUtXWE4rhPFngnryZDrSBHI_vx7tLKJM',
    appId: '1:414915772944:web:d31154ca49548cbc7ac095',
    messagingSenderId: '414915772944',
    projectId: 'servana-8a6f3',
    authDomain: 'servana-8a6f3.firebaseapp.com',
    storageBucket: 'servana-8a6f3.firebasestorage.app',
    measurementId: 'G-KDKKDNZDNB',
  );
}
